apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: chaz.straney@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-cluster-issuer-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: do-token
            key: token
