apiVersion: cert-manager.io/v11
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: chaz.straney@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: do-token
            key: token
