apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: pequod
spec:
  hosts:
  - ssh:
      address: 5.9.209.221
      user: ladmin
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller+worker
  - ssh:
      address: 5.9.209.222
      user: ladmin
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  - ssh:
      address: 5.9.209.223
      user: ladmin
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
  k0s:
    version: 1.24.2+k0s.0
    config:
      spec:
        extensions:
          storage:
            type: openebs_local_storage
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
          calico: null
