apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- server.yaml
- patches/run-as-root.yaml
- patches/configmap-argocd-cm.yaml
- patches/vela-on-repo-server.yaml

namespace: argocd
