resources:
-

helmCharts:
  - repo: https://helm.pomerium.io
    valuesInline:
      authenticate:
        existingTLSSecret: pomerium-tls
        idp:
          provider: "google"
          clientID: YOUR_CLIENT_ID
          clientSecret: YOUR_SECRET
          serviceAccount: YOUR_SERVICE_ACCOUNT
        proxied: false
      proxy:
        existingTLSSecret: pomerium-tls
      databroker:
        existingTLSSecret: pomerium-tls
        storage:
          connectionString: rediss://pomerium-redis-master.pomerium.svc.cluster.local
          type: redis
          clientTLS:
            existingSecretName: pomerium-tls
            existingCASecretKey: ca.crt
      authorize:
        existingTLSSecret: pomerium-tls
      redis:
        enabled: true
        auth:
          enabled: false
        usePassword: false
        generateTLS: false
        tls:
          certificateSecret: pomerium-redis-tls
      ingressController:
        enabled: true
      config:
        rootDomain: localhost.pomerium.io
        existingCASecret: pomerium-tls
        generateTLS: false
