apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: workloads/crossplane-config
    repoURL: git@github.com:metaproblem/metaproblem-bootstrap
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
