apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: workloads/kubevela
    repoURL: git@github.com:metaproblem/metaproblem-bootstrap
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
