apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpayloads.crossplane.metaproblem.io
  namespace: crossplane
spec:
  group: crossplane.metaproblem.io
  names:
    kind: XPayload
    plural: xpayloads
  claimNames:
    kind: Payload
    plural: payloads
  defaultCompositionRef:
    name: payload-composition
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  image:
                    type: string
                  port:
                    type: integer
                  name:
                    type: string
                required:
                - image
                - port
                - name
        required:
        - parameters
