# -apiVersion: kubernetes.crossplane.io/v1alpha1
# kind: ProviderConfig
# metadata:
#   name: kubernetes-provider
#   namespace: crossplane-system
# spec:
#   credentials:
#     source: InjectedIdentity
