# n8n uses the following env vars
# N8N_BASIC_AUTH_ACTIVE=true
# N8N_BASIC_AUTH_USER=<USER>
# N8N_BASIC_AUTH_PASSWORD=<PASSWORD>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - image: n8nio/n8n
        name: n8n
        ports:
        - containerPort: 5678
          name: http
        envFrom:
        - configMapRef:
            name: n8n-configmap
        volumeMounts:
        - mountPath: "/lol"
          name: n8n-volume
      volumes:
      - name: n8n-volume
        persistentVolumeClaim:
          claimName: n8n-pvc
