---
# Source: drone/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone
  labels:
    app: drone
  annotations:
    cert-manager.io/cluster-issuer: "acme-issuer"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "traefik"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: "drone.itscoming.run"
spec:
  rules:
    - host: drone.softchewy.center
      http:
        paths:
          - path: /
            backend:
              serviceName: drone
              servicePort: 80
  tls:
    - hosts:
      - drone.softchewy.center
      secretName: drone-tls
