---
# Source: drone/templates/role-binding-pipeline.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drone-pipeline
  labels:
    app: drone
    chart: "drone-2.4.0"
    release: "drone"
    heritage: "Tiller"
subjects:
  - kind: ServiceAccount
    name: drone-pipeline
    namespace: drone
roleRef:
  kind: ClusterRole
  name: drone-pipeline
  apiGroup: rbac.authorization.k8s.io
