---
# Source: drone/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: drone
  labels:
    app: drone
    release: "drone"
type: Opaque
data:
  secret: "VGN5alU3cG9yZlpsQTVhcUZEb0JSUGJP"

---
