apiVersion: v2
name: openebs
description: Wrapper/Proxy Chart for openebs
# A chart can be either an 'application' or a 'library' chart.
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: openebs
  version: 2.12.1
  repository: https://openebs.github.io/charts
